data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "Shawn (unverified)"
public_key = ""

# Optional. Only used when updating from GitHub releases
[github]
owner = "paritytech"
repo = "polkadot"

[[chains]]
name = "polkadot"
rpc_endpoint = "wss://rpc.polkadot.io"
# Optional. Only used when updating from GitHub releases
genesis_hash = "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3"

[[chains]]
name = "kusama"
rpc_endpoint = "wss://kusama-rpc.polkadot.io"
# Optional. Only used when updating from GitHub releases
genesis_hash = "0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe"

[[chains]]
name = "westend"
rpc_endpoint = "wss://westend-rpc.polkadot.io"
# Optional. Only used when updating from GitHub releases
genesis_hash = "0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e"

[[chains]]
name = "acala"
rpc_endpoint = "wss://acala-rpc-0.aca-api.network"

[[chains]]
name = "moonbeam"
rpc_endpoint = "wss://wss.api.moonbeam.network"

[[chains]]
name = "astar"
rpc_endpoint = "wss://rpc.astar.network"

[[chains]]
name = "centrifuge"
rpc_endpoint = "wss://fullnode.parachain.centrifuge.io"

[[chains]]
name = "clover-mainnet"
rpc_endpoint = "wss://rpc-para.clover.finance"

[[chains]]
name = "hydradx"
rpc_endpoint = "wss://rpc-01.hydradx.io"
